#pragma once

#include "NativeGameplayTags.h"

namespace BSGameplayTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_BasicAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Evade);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Dash);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_BasicAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_BasicAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Evade);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Dash);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReaction_Flinch);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_BasicAttack_ComboInput);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combo_WindowOpen);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combo_WindowClose);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_MeleeTrace_Start);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_MeleeTrace_End);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_SpawnProjectile);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_Death);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_HitReaction_Begin);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_HitReaction_End);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DamageType_Melee);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DamageType_Fire);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DamageType_Ice);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Invulnerable);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Immune_Melee);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Immune_Fire);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Immune_Ice);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attacking);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combo);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_FaceTarget);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Evading);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dashing);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_StaminaRegenDelay);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_LockOn);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_SuperArmor);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_HitReacting);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Block_Move);

	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_StaminaCost);
}
